### ISSUE TITLE
Cannot read properties of undefined: reading 'registerSchemesAsPrivileged'

### ISSUE THREAD

**Issue by jogibear9988** [electron/remote#88] opened 2021-10-19 11:07 UTC
My new code looks this:

	let win

	let { app, protocol, BrowserWindow } = require('@electron/remote/main');
	const fs = require("fs");
	const path = require('path');
	let { URL } = require("url");

	require('@electron/remote/main').initialize()

	const checkImportRegex = /(import|export)(\s*{?\*?[\s\w,$]*}?\s*(as)?[\s\w]*from\s|[\s]*)['\"]([^\.\/][\w\/\-@.]*?)['\"]/g;
	let checkRelativeImportRegex = new RegExp("(import|export)(\\s*{?\\*?[\\s\\w,$]*}?\\s*(as)?[\\s\\w]*from\\s|[\\s]*)['\\\"]([\\.\\/][\\w\\/\\-@.]*?)['\\\"]", 'g');

	protocol.registerSchemesAsPrivileged([{scheme: 'app', privileges: { secure: true, standard: true } }]);
	let createProtocol = (scheme, normalize = true) => {
		protocol.registerBufferProtocol(scheme,
			async (request, respond) => {

....

**Comment by ckerr** [comment] 2021-10-19 13:19
Hey @jogibear9988,

I haven't tested the code but it looks like the issue is that you're using `protocol` before the ready event of the app module gets emitted. I believe `protocol` here is re-exported from Electron and the [Electron docs say the protocol module can only be used after ready.](https://www.electronjs.org/docs/latest/api/protocol)

Marking as a question for clarification. If you're already waiting for ready, could you please upload a small test case as a gist and link to it here?

**Closed as completed** 2021-10-19 14:50 UTC
